In [1]:
import numpy as np

import cv2

img = cv2.imread('logo.png')

imgray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

ret, thresh = cv2.threshold(imgray, 20, 255, 0)

contours, hierarchy = cv2.findContours(thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_NONE)

print("Number of contours = " + str(len(contours)))

print(contours[0])

cv2.drawContours(img, contours, -1, (0, 255, 0), 3)

# cv2.drawContours(imgray, contours, -1, (0, 255, 0), 3)

cv2.imshow('Image', img)
cv2.imshow('thresh', imgray)
cv2.imshow('Image GRAY', imgray)

cv2.waitKey(0)

cv2.destroyAllWindows()#close window

Number of contours = 12
[[[412 389]]

 [[412 390]]

 [[412 391]]

 [[412 392]]

 [[412 393]]

 [[412 394]]

 [[412 395]]

 [[412 396]]

 [[412 397]]

 [[412 398]]

 [[412 399]]

 [[412 400]]

 [[412 401]]

 [[412 402]]

 [[412 403]]

 [[412 404]]

 [[412 405]]

 [[412 406]]

 [[412 407]]

 [[412 408]]

 [[412 409]]

 [[412 410]]

 [[412 411]]

 [[412 412]]

 [[412 413]]

 [[412 414]]

 [[412 415]]

 [[412 416]]

 [[412 417]]

 [[412 418]]

 [[412 419]]

 [[412 420]]

 [[412 421]]

 [[412 422]]

 [[413 422]]

 [[414 422]]

 [[415 422]]

 [[416 422]]

 [[417 422]]

 [[418 422]]

 [[419 422]]

 [[420 422]]

 [[420 421]]

 [[420 420]]

 [[420 419]]

 [[420 418]]

 [[420 417]]

 [[420 416]]

 [[420 415]]

 [[420 414]]

 [[420 413]]

 [[420 412]]

 [[420 411]]

 [[420 410]]

 [[420 409]]

 [[420 408]]

 [[420 407]]

 [[420 406]]

 [[420 405]]

 [[420 404]]

 [[420 403]]

 [[420 402]]

 [[420 401]]

 [[420 400]]

 [[420 399]]

 [[421 398]]

 [[422 397]]

 [[423 397]]

 [[424 396]]

 [[425 396

resources

https://docs.opencv.org/4.x/d4/d73/tutorial_py_contours_begin.html